### ISSUE TITLE
bug LaunchActivity 的生命周期无法执行

### ISSUE THREAD

**Issue by fangding** [13217300237/ActivityHookDemo#1]
发现一个致命的bug：hook之后，LaunchActivity 的生命周期完全无法执行了，例如：onRestar、onResume、onPause、onStop 等等

**Comment by andych008** [comment]
> 发现一个致命的bug：hook之后，LaunchActivity 的生命周期完全无法执行了，例如：onRestar、onResume、onPause、onStop 等等

准确讲，有onStart、onResume，没有onPause、onStop

**Comment by 13217300237** [comment]
感谢，有时间我会处理



---原始邮件---
发件人: "喵叔catuncle"<notifications@github.com&gt;
发送时间: 2019年11月15日(星期五) 晚上8:43
收件人: "18598925736/ActivityHookDemo"<ActivityHookDemo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [18598925736/ActivityHookDemo] bug LaunchActivity 的生命周期无法执行 (#1)


 
发现一个致命的bug：hook之后，LaunchActivity 的生命周期完全无法执行了，例如：onRestar、onResume、onPause、onStop 等等
  
准确讲，有onStart、onResume，没有onPause、onStop

**Comment by andych008** [comment]
补充：只有api>=28存在这个问题

**Comment by 13217300237** [comment]
我当时只适配了ask 28，新的系统我没有尝试。你有时间就试试看能不能解决哦



---原始邮件---
发件人: "喵叔catuncle"<notifications@github.com&gt;
发送时间: 2019年11月15日(星期五) 晚上9:27
收件人: "18598925736/ActivityHookDemo"<ActivityHookDemo@noreply.github.com&gt;;
抄送: "18598925736"<545679452@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [18598925736/ActivityHookDemo] bug LaunchActivity 的生命周期无法执行 (#1)



补充：api&gt;=29有这个问题

**Comment by andych008** [comment]
我正要发一个pr，android 10上会crash

**Comment by 13217300237** [comment]
已经验证，确实在29的机器上，启动作为Launcher的MainActivity之后，再跳转到其他未注册的Activity，MainActivity的生命周期函数本来应该执行onPause和onStop，回来的时候应该执行onRestart-onStart-onResume,但是都没有执行。已经排期在处理了。

**Comment by 13217300237** [comment]
bug已解决，是一个return true引起的问题。应该是 return false。
具体的解释一下：
 android.os.handler 这个类有 3个 callback，按照优先级，依次是 msg的callback，自己成员变量mCallback，自己的成员方法 handleMessage()
  其中，msg.callback一般很少用，但是它是最优先的，如果有一个Message.存在callback非空成员,那么它是先执行，后面两个就没戏了。
   如果 handler自己的成员变量mCallback，非空，那么 handlerMessage()方法就没戏了
   前面两个都执行，那么handlerMessage才会执行。
   我的hook思路是用代理的Handler.Callback替换掉ActivityThread$mH中的mCallback，然后居然return true，导致原本handlerMessage()中的逻辑不能执行。
是我的疏忽，当时测试不充分。
感谢你的提醒。拉取最新代码，现在可以了。
